language: node_js
node_js:
- '7'
cache: yarn
script: npm run unit
before_deploy: npm run build
deploy:
  provider: firebase
  token:
    secure: nSH8F2hPEbA0BOJ2qyEsHos7ZdTCoReG8FVMuPfI+/7erRgt7TQLVc+yADIULxKomY0VzNdbc+yKuGTA7fJMRPHJRNIfJllrZtoVCxFgZtINmmc5qjNLIWX5GAef2l3ge8/UMuxAZed7CfIBlU4vnEWwLLZbKkgFNuxYMWcrLdbIn/P6INQjHUB51l/aGqu9hsiJTV1Rs30q02N6UQKIlH8qXeOsbEyV6xtdkYlqAJ+XrDYPepgwWEUli5wZDq7VcEluRyaXOUUsaIOEz2aeILFVNA99LkWG0Oa+ucTC1hbBKEZMroE3GmnAcyK694Nq2UZDgXTl9oEdAOtoV85j23oa4ddCsSEuPbFBrp3Rdh/RpmfVB64kxVQKu1m9tg4PH9iBwRClDuV/TAwYRF0ooHGD9vwmFWxm9x+UD7BNuwHhiTYk4NHUn31L6+X4KJwt+L4PMuhJZICz5RDaOVzaZIuALI1KfCwwZxpTfpdcxChfvnuoHKj5St6Nz2b9rXrg2zqRE2RvP++ey5LiMgw14qaGcqQ1eu9A2aqZp8b+G/pqy8j9GDKdkhYPVY2a1/1nrqHpEGQxG9oWO5GcWStOA6MfiJRrcx+nTyuJ3D7OuMjRTW3utGSIw8b6RMjP3trGQFOn7AJpeOJLSw2TODXvdIrBLUiyaSH54GLDGnDViPI=
  project: levi-99180
