language: node_js
node_js:
- '7'
cache: yarn

before_script:
  - npm install -g firebase-tools
  - npm install -g wintersmith

script: npm run unit

after_success:
  - npm run build
  - firebase deploy --token=${FIREBASE_API_TOKEN}