language: node_js
node_js:
- '7'
cache: yarn
script: npm run unit

before_deploy: npm run build

deploy:
  provider: firebase
  token:
    secure: secure: t8C8o0j3CRVHl/2j5TnjWs8oHFSa7THrre/rGxwvmPjS7q3zCuRrm8UREh7dg33ZK1rSJUc/H7ikWspEwOf5tQfeJwZR5M8Iz+0ysWk9Wa0X07UpyaRPBFshNopXJczjeM5cQB3lBZKP3odGbqakSxdf6vUmbarMX6fVSPVuX/4cvxg8y7VDkPucL62AIDwUOUvVrV4BV5ylOueiuL4/l57qNWOyenyy2lNJIcFudn/TcIi9YbfWY/RdSSzgiwEoX7PoaXnP2T2JEoBV2+oPyv4BPo+oYPxMUfcyM8br9XR8DN4DxPa49CLFsBsQsyVA6WTUOVJGR5NYnu5qy/3mGU//5TLH/Fx8wH7T/fhKzWucADLr+blMQUOdJ7qvc9pgR8Gw9pdoDkJHGsQX1jrBZ7FlZNv7Ke6Ifd1O1QmYQSyl56pZXgQx/ioDiPgTVdXmaiXLmPZFwmjZx1POFXGhPlzY8UIYCxz2eKhalszaTj9OCtN6hwEMzZfsAg/VoRADqMVU/Y/GYx8NqZTGYrsZ60TyXXfcjrYuVRFImIImemAqlCP7FikjMil9KMvzO9Mw9LhjUr505hLoPbuJ0dWU/XeCBgCRLqbKhPI/n34HHt8JgQ0wOX8tn17XnsSap46Wjc1HUw7UJlTaIoUWT/FNoV1up6Ti+Rgk4AIXd6J1dQs=
  project: levi-99180
