export const UPDATE_MONTHLY_FIELD = 'UPDATE_MONTHLY_FIELD';
export const CALCULATE_MONTHLY_TOTAL_RAISED = 'CALCULATE_MONTHLY_TOTAL_RAISED';
export const CALCULATE_MONTHLY_BALANCE = 'CALCULATE_MONTHLY_BALANCE';
