// auth
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';

// organization
export const ORGANIZATION_LOADED = 'ORGANIZATION_LOADED';
export const ORGANIZATIONS_LOADED = 'ORGANIZATIONS_LOADED';
export const ORGANIZATION_TYPES_LOADED = 'ORGANIZATION_TYPES_LOADED';

// reports
export const CHURCH_REPORTS_LOADED = 'CHURCH_REPORTS_LOADED';
export const CHURCH_REPORT_LOADED = 'CHURCH_REPORT_LOADED';
export const CHURCH_REPORT_UPDATED = 'CHURCH_REPORT_UPDATED';

export const DISTRICT_REPORTS_LOADED = 'DISTRICT_REPORTS_LOADED';
export const DISTRICT_REPORT_LOADED = 'DISTRICT_REPORT_LOADED';
export const DISTRICT_REPORT_OPENING_FUND_UPDATED = 'DISTRICT_REPORT_OPENING_FUND_UPDATED';

export const SOURCES_LOADED = 'SOURCES_LOADED';
export const SOURCE_NAME_UPDATED = 'SOURCE_NAME_UPDATED'; // these do the
export const SOURCE_AMOUNT_UPDATED = 'SOURCE_AMOUNT_UPDATED'; // same thing
export const SOURCE_UPDATED = 'SOURCE_UPDATED';

export const EXPENSES_LOADED = 'EXPENSES_LOADED';
export const EXPENSE_UPDATED = 'EXPENSES_UPDATED';
export const EXPENSE_ADDED = 'EXPENSE_ADDED';
